### ISSUE TITLE
Full build of site is flaky

### ISSUE THREAD

**Issue by ajessup** [spiffe/spiffe.io#250]
Looking at the Netlify deploy logs (https://app.netlify.com/sites/spiffe/deploys) it seems that there's often sporadic failures that can be resolved by just retrying the build. At least a few of these have failed with:

```
10:45:13 AM: ERROR 2022/07/29 14:45:13 Failed to get JSON resource "https://api.github.com/repos/spiffe/spire/releases": Failed to retrieve remote file: Forbidden
```

Examples:
* https://app.netlify.com/sites/spiffe/deploys/62e3f24cd5d25d000889060b
* https://app.netlify.com/sites/spiffe/deploys/62d9981f78cd2b12d4539619

It would be nice to make this code a little more resilient (perhaps retries?) to minimize this flakiness.

**Comment by mchurichi** [comment]
This error started to show up some time ago and it's getting more frequent. I don't know what the cause is but I've only seen this on Netlify, not locally, so I guess it may be related to their build system.
Anyways, as the error comes from Hugo trying to dynamically load content the fix is not as straightforward as one could think, as it does not allow to set a retry policy. #251 should fix this by removing the dynamic loading and pre-loading (with retries) the json even before Hugo starts.
